name: dough
description: Dough provides widgets for building smooshy user interfaces.
version: 2.0.0
repository: https://github.com/josiahsrc/dough/tree/master/packages/dough
homepage: https://josiahsaunders.com/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.3
  provider: ^6.0.0
  vector_math: ^2.1.0

dev_dependencies:
  build_runner: ^2.0.4    
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  very_good_analysis: ^2.0.0
