name: dough_sensors
description: Smooshy widgets that use sensors.
version: 0.0.2
repository: https://github.com/josiahsrc/dough/tree/master/packages/dough_sensors
homepage: https://josiahsaunders.com/

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  sensors: ^2.0.3
  dough: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
