name: dough_sensors
description: Smooshy widgets that use sensors.
version: 0.0.1
repository: https://github.com/josiahsrc/dough/tree/master/packages/dough_sensors
homepage: https://josiahsaunders.com/

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  provider: ^6.1.1
  sensors: ^2.0.3
  vector_math: ^2.1.4
  dough:
    path: ../dough

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
